// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rawzqrhnoyeoqzsnnrug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhd3pxcmhub3llb3F6c25ucnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTEyMTAsImV4cCI6MjA2OTQ4NzIxMH0.pQ2QjOF5hDVEu6BivKAi5as_tHlIWt-a5oV7p9i-tWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});